branches:
  only:
    - master

sudo: required
dist: trusty
language: c++
compiler: g++
notifications:
  - email: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq bison flex

before_script:
  - bison --version
  - flex --version

script:
  - make 
  - testsuit.sh
