#include <stdio.h>
int main()
{
static double var[17] = {0};
static double intbuf[1]   = {0};
static char   str[]       = ", \0...\n\0";
static char   printInt[]  = "%d\n";
static char   printStr[]  = "%s\n";
static char   writeInt[]  = "%d";
static char   writeStr[]  = "%s";
static char   readInt[]   = "%d";
asm(
"leaq %[var], %% r15\n\t"
"leaq %[str], %% r14\n\t"
"jmp lbl0\n\t"

"\nfibonacci:\n\t"
"# --[ NS := FH FuncHead FH ]-- \n\t"
"pushq %%rbp\n\t"
"pushq %%r15\n\t"
"movq %%rsp, %%rbp\n\t"
"subq $128, %%rsp\n\t"
"movq %%rsp, %%r15 \n\t"
"# --[ P0 := n FuncParam n ]-- \n\t"
"movq %%rdi, 16(%%r15)\n\t"
"jmp lbl2\n\t"

"\nlbl2:\n\t"
"# --[ _id9 := n LessThan 3 ]-- \n\t"
"movq 16(%%r15), %%rax\n\t"
"movq $3, %%rbx\n\t"
"cmpq %%rbx, %%rax\n\t"
"jge lbl3\n\t"
"movq %%rax, 24(%%r15)\n\t"
"# --[ 1 := 1 Return 1 ]-- \n\t"
"movq $1, %%rax\n\t"
"# --[ FF := FF FuncFoot FF ]-- \n\t"
"movq %%rbp, %%rsp\n\t"
"popq %%r15\n\t"
"popq %%rbp\n\t"
"ret\n\t"
"jmp lbl4\n\t"

"\nlbl3:\n\t"
"# --[ _id21 := n Subtraction 1 ]-- \n\t"
"movq 16(%%r15), %%rax\n\t"
"movq $1, %%rbx\n\t"
"subq %%rbx, %%rax\n\t"
"movq %%rax, 56(%%r15)\n\t"
"# --[ NS := FCH FuncCallHead FCH ]-- \n\t"
"pushq %%rax\n\t"
"pushq %%rbx\n\t"
"# --[ P0 := _id21 FuncCallParam _id21 ]-- \n\t"
"movq 56(%%r15), %%rdi\n\t"
"# --[ _id22 := fibonacci FuncCall fibonacci ]-- \n\t"
"call fibonacci\n\t"
"movq %%rax, 72(%%r15)\n\t"
"# --[ NS := FCF FuncCallFoot FCF ]-- \n\t"
"popq %%rbx\n\t"
"popq %%rax\n\t"
"# --[ _id27 := n Subtraction 2 ]-- \n\t"
"movq 16(%%r15), %%rax\n\t"
"movq $2, %%rbx\n\t"
"subq %%rbx, %%rax\n\t"
"movq %%rax, 96(%%r15)\n\t"
"# --[ NS := FCH FuncCallHead FCH ]-- \n\t"
"pushq %%rax\n\t"
"pushq %%rbx\n\t"
"# --[ P0 := _id27 FuncCallParam _id27 ]-- \n\t"
"movq 96(%%r15), %%rdi\n\t"
"# --[ _id28 := fibonacci FuncCall fibonacci ]-- \n\t"
"call fibonacci\n\t"
"movq %%rax, 112(%%r15)\n\t"
"# --[ NS := FCF FuncCallFoot FCF ]-- \n\t"
"popq %%rbx\n\t"
"popq %%rax\n\t"
"# --[ _id29 := _id22 Addition _id28 ]-- \n\t"
"movq 72(%%r15), %%rax\n\t"
"movq 112(%%r15), %%rbx\n\t"
"addq %%rbx, %%rax\n\t"
"movq %%rax, 120(%%r15)\n\t"
"# --[ _id29 := _id29 Return _id29 ]-- \n\t"
"movq 120(%%r15), %%rax\n\t"
"# --[ FF := FF FuncFoot FF ]-- \n\t"
"movq %%rbp, %%rsp\n\t"
"popq %%r15\n\t"
"popq %%rbp\n\t"
"ret\n\t"
"jmp lbl4\n\t"

"\nlbl4:\n\t"
"# --[ NS := FF FuncFoot FF ]-- \n\t"
"movq %%rbp, %%rsp\n\t"
"popq %%r15\n\t"
"popq %%rbp\n\t"
"ret\n\t"

"\nlbl0:\n\t"
"# --[ fibonacci := _id35 Assign _id35 ]-- \n\t"
"movq 8(%%r15), %%rax\n\t"
"movq %%rax, 0(%%r15)\n\t"
"# --[ n := 1 Assign 1 ]-- \n\t"
"movq $1, %%rax\n\t"
"movq %%rax, 16(%%r15)\n\t"
"jmp lbl5\n\t"

"\nlbl5:\n\t"
"# --[ _id56 := n LessOrEqual 16 ]-- \n\t"
"movq 16(%%r15), %%rax\n\t"
"movq $16, %%rbx\n\t"
"cmpq %%rbx, %%rax\n\t"
"jg lbl6\n\t"
"movq %%rax, 32(%%r15)\n\t"
"# --[ NS := FCH FuncCallHead FCH ]-- \n\t"
"pushq %%rax\n\t"
"pushq %%rbx\n\t"
"# --[ P0 := n FuncCallParam n ]-- \n\t"
"movq 16(%%r15), %%rdi\n\t"
"# --[ _id46 := fibonacci FuncCall fibonacci ]-- \n\t"
"call fibonacci\n\t"
"movq %%rax, 64(%%r15)\n\t"
"# --[ NS := FCF FuncCallFoot FCF ]-- \n\t"
"popq %%rbx\n\t"
"popq %%rax\n\t"
"# --[ NS := FCH FuncCallHead FCH ]-- \n\t"
"pushq %%rax\n\t"
"pushq %%rbx\n\t"
"# --[ _id49 := write FuncCall _id46 ]-- \n\t"
"movq 64(%%r15), %%rbx\n\t"
"leaq %[writeInt], %%rdi\n\t"
"movq %%rbx, %%rsi\n\t"
"movq $0, %%rax\n\t"
"call printf\n\t"
"movq %%rax, 80(%%r15)\n\t"
"# --[ NS := FCF FuncCallFoot FCF ]-- \n\t"
"popq %%rbx\n\t"
"popq %%rax\n\t"
"# --[ _id47 := _id47 String _id47 ]-- \n\t"
"leaq 0(%%r14), %%rax\n\t"
"movq %%rax, 96(%%r15)\n\t"
"# --[ NS := FCH FuncCallHead FCH ]-- \n\t"
"pushq %%rax\n\t"
"pushq %%rbx\n\t"
"# --[ _id51 := write FuncCall _id47 ]-- \n\t"
"movq 96(%%r15), %%rbx\n\t"
"leaq %[writeStr], %%rdi\n\t"
"movq %%rbx, %%rsi\n\t"
"movq $0, %%rax\n\t"
"call printf\n\t"
"movq %%rax, 104(%%r15)\n\t"
"# --[ NS := FCF FuncCallFoot FCF ]-- \n\t"
"popq %%rbx\n\t"
"popq %%rax\n\t"
"# --[ _id60 := n Addition 1 ]-- \n\t"
"movq 16(%%r15), %%rax\n\t"
"movq $1, %%rbx\n\t"
"addq %%rbx, %%rax\n\t"
"movq %%rax, 112(%%r15)\n\t"
"# --[ n := _id60 Assign _id60 ]-- \n\t"
"movq 112(%%r15), %%rax\n\t"
"movq %%rax, 16(%%r15)\n\t"
"jmp lbl5\n\t"

"\nlbl6:\n\t"
"# --[ _id68 := _id68 String _id68 ]-- \n\t"
"leaq 3(%%r14), %%rax\n\t"
"movq %%rax, 120(%%r15)\n\t"
"# --[ NS := FCH FuncCallHead FCH ]-- \n\t"
"pushq %%rax\n\t"
"pushq %%rbx\n\t"
"# --[ _id69 := write FuncCall _id68 ]-- \n\t"
"movq 120(%%r15), %%rbx\n\t"
"leaq %[writeStr], %%rdi\n\t"
"movq %%rbx, %%rsi\n\t"
"movq $0, %%rax\n\t"
"call printf\n\t"
"movq %%rax, 128(%%r15)\n\t"
"# --[ NS := FCF FuncCallFoot FCF ]-- \n\t"
"popq %%rbx\n\t"
"popq %%rax\n\t"
: [var]      "+g" (var),
  [intbuf]   "+g" (intbuf),
  [str]      "+g" (str),
  [printInt] "+g" (printInt),
  [printStr] "+g" (printStr),
  [writeInt] "+g" (writeInt),
  [writeStr] "+g" (writeStr),
  [readInt]  "+g" (readInt)
:
: "rax",
  "rbx",
  "rcx",
  "rdx",
  "rdi",
  "rsi",
  "al",
  "bl",
  "r15",
  "r14"
);
}
